<xml><status request_id="4966e1b4-e639-4afd-aad6-193fc627a5301595464968069" response_time="00:00:00:074"><client_id>Fujitsu_capacity</client_id><status_code>SUCCESS</status_code></status><results results_count="1"><system><system_id>0537091011</system_id><sys_serial_no>451716000032</sys_serial_no><sys_model>AFF8040</sys_model><sys_type>AFF</sys_type><hostname>sindsjnasmcp01n2</hostname><sys_version>9.5P11</sys_version><sys_top_domain>db</sys_top_domain><sys_domain>list.db.com</sys_domain><sys_remote_support_status/><customer_name>Deutsche Bank</customer_name><customer_id>1033890</customer_id><group_name>DEUTSCHE_BANK</group_name><group_id>42817753</group_id><site_name>DEUTSCHE BANK - SG - DSJ</site_name><site_id>2699579</site_id><image_id/><derived_mcc_config_type>4_Node_Fabric</derived_mcc_config_type><is_all_flash_optimized>true</is_all_flash_optimized><transport_method>smtp</transport_method><is_aods_capable>false</is_aods_capable><is_aods_enabled>false</is_aods_enabled><job_id/><system_device_type/><grid_name/><service_tag/><platform_type>ONTAP</platform_type><is_flexpod/><project_id/><sys_genre></sys_genre><capacity_pool_sn/><service_tier>DEFAULT</service_tier><ha_group><partner_system_id>0537091045</partner_system_id><partner_hostname>sindsjnasmcp01n1</partner_hostname><partner_sys_serial_no/></ha_group><cluster><cluster_name>sindsjnasmcp01</cluster_name><cluster_identifier>9a96bf6e-b084-11e9-9960-00a098b37b01</cluster_identifier><cluster_member_identifier>04eba8b0-b076-11e9-a578-00a098b3778d</cluster_member_identifier><cluster_nodes_summary>http://restprd.corp.netapp.com/asup-rest-interface/ASUP_DATA/client_id/Fujitsu_capacity/cluster_identifier/9a96bf6e-b084-11e9-9960-00a098b37b01</cluster_nodes_summary></cluster><asups start="1" limit="50" total_results_count="1" results_count="1"><asup><biz_key>C|9A96BF6E-B084-11E9-9960-00A098B37B01|8404882946|451716000032</biz_key><asup_id>2020071809480304</asup_id><asup_subject>HA Group Notification (WEEKLY_LOG) NOTICE</asup_subject><asup_type>DOT-REGULAR</asup_type><asup_gen_date>2020-07-19T00:04:13+08:00</asup_gen_date><asup_received_date>Sat Jul 18 09:47:29 PDT 2020</asup_received_date><asup_gen_zone>+08</asup_gen_zone><asup_is_minimal>false</asup_is_minimal><sys_version>9.5P11</sys_version><sys_operating_mode>Cluster-Mode</sys_operating_mode><hostname>sindsjnasmcp01n2</hostname><sys_domain>list.db.com</sys_domain><cluster_name>sindsjnasmcp01</cluster_name><cluster_identifier>9a96bf6e-b084-11e9-9960-00a098b37b01</cluster_identifier><is_perf_truncated/><is_manual/><job_id/><system_device_type/><grid_name/><project_id/><perf_dashboard_url/><list results_count="1"><content><name>VOLUME.XML</name><data><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE T_VOLUME [
<!ELEMENT T_VOLUME (asup:TABLE_INFO,asup:ROW*,asup:ABORT?)>
<!ATTLIST T_VOLUME xmlns CDATA #FIXED "http://asup_search.netapp.com/ns/T_VOLUME/1.0">
<!ATTLIST T_VOLUME xmlns:asup CDATA #FIXED "http://asup_search.netapp.com/ns/ASUP/1.1">
<!ATTLIST T_VOLUME smf_table_name CDATA #REQUIRED>
<!ATTLIST T_VOLUME smf_table_desc CDATA #REQUIRED>
<!ATTLIST T_VOLUME col_time_us CDATA #REQUIRED>
<!ATTLIST T_VOLUME cluster_uuid CDATA "0">
<!ATTLIST T_VOLUME node_uuid CDATA #REQUIRED>
<!ATTLIST T_VOLUME node_sn CDATA #REQUIRED>
<!ATTLIST T_VOLUME node_system_id CDATA #REQUIRED>
<!ATTLIST T_VOLUME data_scope (cluster|node) #REQUIRED>
<!ELEMENT asup:TABLE_INFO (asup:field*,asup:ABORT?)>
<!ELEMENT asup:field (asup:tag,asup:smf_name,asup:ui_name,asup:type,asup:qualification,asup:remap)>
<!ELEMENT asup:tag (#PCDATA)>
<!ELEMENT asup:smf_name (#PCDATA)>
<!ELEMENT asup:ui_name (#PCDATA)>
<!ELEMENT asup:type (#PCDATA)>
<!ELEMENT asup:list (asup:li+)>
<!ELEMENT asup:li (#PCDATA)>
<!ATTLIST asup:type is_list (true|false) "false">
<!ELEMENT asup:qualification (#PCDATA)>
<!ELEMENT asup:remap (#PCDATA)>
<!ELEMENT asup:ABORT (#PCDATA)>
<!ELEMENT asup:ROW (vs,vol,dsid,msid,aggr,state,type,style,styleEx,policy,usr,grp,security_style,unix_perm,j_path,j_path_src,j_actv,parent,vsroot,comment,size,avail,total,used,pcnt_used,exp_avail_size,over_provisioned_size,snap_rsrv_avail_size,nearly_full_threshold,full_threshold,autosz,max_autosz,min_autosz,autosz_grow_thresh_pcnt,autosz_shrink_thresh_pcnt,autosz_mode,files,files_used,inofile_version,maxdir_size,space_guarantee,is_space_guarantee_en,min_rdahead,atime_update,snapdir_access,pcnt_snap_space,snap_policy,c_time,lang,oem_char_set,nfs_char_set,max_write_alloc_blks,name_ordinal,is_clust_vol,used_snap_rsrv_pcnt,clone_vol,anti_virus_on_access_policy,vol_uuid,load_share_src,move_target,fs_inconsistency,is_rdonly,i_uuid,p_uuid,nvfail_option,in_nvfailed_state,dr_force_nvfail_option,blk_type,hya_eligibility,hya_wc_ineligibility_reason,caching_policy,cache_retention_priority,autobalance_aggr_enabled,role,fgMsid,fgIndex,fgUuid,maxConstSize,isFg,isFgQtreeEnabled,isMoveDestInCutover,is_encrypted,encryption_key_id,appName,appUuid,extent_size,tiering_policy,sl_type,tiering_min_cooling_days,logicalUsed,logicalUsedPercent,logicalAvailable,afsLogicalUsed,snapLogicalUsed,logicalSpaceReporting,logicalSpaceEnforcement,perfTierInactiveUserData)>
<!ATTLIST asup:ROW col_time_us CDATA #REQUIRED>
<!ELEMENT vs (#PCDATA)><!ELEMENT vol (#PCDATA)><!ELEMENT dsid (#PCDATA)><!ELEMENT msid (#PCDATA)><!ELEMENT aggr (#PCDATA)><!ELEMENT state (#PCDATA)><!ELEMENT type (#PCDATA)><!ELEMENT style (#PCDATA)><!ELEMENT styleEx (#PCDATA)><!ELEMENT policy (#PCDATA)><!ELEMENT usr (#PCDATA)><!ELEMENT grp (#PCDATA)><!ELEMENT security_style (#PCDATA)><!ELEMENT unix_perm (#PCDATA)><!ELEMENT j_path (#PCDATA)><!ELEMENT j_path_src (#PCDATA)><!ELEMENT j_actv (#PCDATA)><!ELEMENT parent (#PCDATA)><!ELEMENT vsroot (#PCDATA)><!ELEMENT comment (#PCDATA)><!ELEMENT size (#PCDATA)><!ELEMENT avail (#PCDATA)><!ELEMENT total (#PCDATA)><!ELEMENT used (#PCDATA)><!ELEMENT pcnt_used (#PCDATA)><!ELEMENT exp_avail_size (#PCDATA)><!ELEMENT over_provisioned_size (#PCDATA)><!ELEMENT snap_rsrv_avail_size (#PCDATA)><!ELEMENT nearly_full_threshold (#PCDATA)><!ELEMENT full_threshold (#PCDATA)><!ELEMENT autosz (#PCDATA)><!ELEMENT max_autosz (#PCDATA)><!ELEMENT min_autosz (#PCDATA)><!ELEMENT autosz_grow_thresh_pcnt (#PCDATA)><!ELEMENT autosz_shrink_thresh_pcnt (#PCDATA)><!ELEMENT autosz_mode (#PCDATA)><!ELEMENT files (#PCDATA)><!ELEMENT files_used (#PCDATA)><!ELEMENT inofile_version (#PCDATA)><!ELEMENT maxdir_size (#PCDATA)><!ELEMENT space_guarantee (#PCDATA)><!ELEMENT is_space_guarantee_en (#PCDATA)><!ELEMENT min_rdahead (#PCDATA)><!ELEMENT atime_update (#PCDATA)><!ELEMENT snapdir_access (#PCDATA)><!ELEMENT pcnt_snap_space (#PCDATA)><!ELEMENT snap_policy (#PCDATA)><!ELEMENT c_time (#PCDATA)><!ELEMENT lang (#PCDATA)><!ELEMENT oem_char_set (#PCDATA)><!ELEMENT nfs_char_set (#PCDATA)><!ELEMENT max_write_alloc_blks (#PCDATA)><!ELEMENT name_ordinal (#PCDATA)><!ELEMENT is_clust_vol (#PCDATA)><!ELEMENT used_snap_rsrv_pcnt (#PCDATA)><!ELEMENT clone_vol (#PCDATA)><!ELEMENT anti_virus_on_access_policy (#PCDATA)><!ELEMENT vol_uuid (#PCDATA)><!ELEMENT load_share_src (#PCDATA)><!ELEMENT move_target (#PCDATA)><!ELEMENT fs_inconsistency (#PCDATA)><!ELEMENT is_rdonly (#PCDATA)><!ELEMENT i_uuid (#PCDATA)><!ELEMENT p_uuid (#PCDATA)><!ELEMENT nvfail_option (#PCDATA)><!ELEMENT in_nvfailed_state (#PCDATA)><!ELEMENT dr_force_nvfail_option (#PCDATA)><!ELEMENT blk_type (#PCDATA)><!ELEMENT hya_eligibility (#PCDATA)><!ELEMENT hya_wc_ineligibility_reason (#PCDATA)><!ELEMENT caching_policy (#PCDATA)><!ELEMENT cache_retention_priority (#PCDATA)><!ELEMENT autobalance_aggr_enabled (#PCDATA)><!ELEMENT role (#PCDATA)><!ELEMENT fgMsid (#PCDATA)><!ELEMENT fgIndex (#PCDATA)><!ELEMENT fgUuid (#PCDATA)><!ELEMENT maxConstSize (#PCDATA)><!ELEMENT isFg (#PCDATA)><!ELEMENT isFgQtreeEnabled (#PCDATA)><!ELEMENT isMoveDestInCutover (#PCDATA)><!ELEMENT is_encrypted (#PCDATA)><!ELEMENT encryption_key_id (#PCDATA)><!ELEMENT appName (#PCDATA)><!ELEMENT appUuid (#PCDATA)><!ELEMENT extent_size (#PCDATA)><!ELEMENT tiering_policy (#PCDATA)><!ELEMENT sl_type (#PCDATA)><!ELEMENT tiering_min_cooling_days (#PCDATA)><!ELEMENT logicalUsed (#PCDATA)><!ELEMENT logicalUsedPercent (#PCDATA)><!ELEMENT logicalAvailable (#PCDATA)><!ELEMENT afsLogicalUsed (#PCDATA)><!ELEMENT snapLogicalUsed (#PCDATA)><!ELEMENT logicalSpaceReporting (#PCDATA)><!ELEMENT logicalSpaceEnforcement (#PCDATA)><!ELEMENT perfTierInactiveUserData (#PCDATA)>]>

<T_VOLUME col_time_us="1279569537850" smf_table_name="volume" smf_table_desc="Volume" cluster_uuid="9a96bf6e-b084-11e9-9960-00a098b37b01" node_uuid="04eba8b0-b076-11e9-a578-00a098b3778d" node_system_id="0537091011" node_sn="451716000032" data_scope="node" xmlns="http://asup_search.netapp.com/ns/T_VOLUME/1.0" xmlns:asup="http://asup_search.netapp.com/ns/ASUP/1.1" >
<asup:TABLE_INFO>
<asup:field>
	<asup:tag>vs</asup:tag>
	<asup:smf_name>vserver</asup:smf_name>
	<asup:ui_name>Vserver Name</asup:ui_name>
	<asup:type>vserver_name</asup:type>
	<asup:qualification>key</asup:qualification>
	<asup:remap>hash</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>vol</asup:tag>
	<asup:smf_name>volume</asup:smf_name>
	<asup:ui_name>Volume Name</asup:ui_name>
	<asup:type>volume_name</asup:type>
	<asup:qualification>key</asup:qualification>
	<asup:remap>hash</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>dsid</asup:tag>
	<asup:smf_name>dsid</asup:smf_name>
	<asup:ui_name>Volume Data Set ID</asup:ui_name>
	<asup:type>unsigned64</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>msid</asup:tag>
	<asup:smf_name>msid</asup:smf_name>
	<asup:ui_name>Volume Master Data Set ID</asup:ui_name>
	<asup:type>unsigned64</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>aggr</asup:tag>
	<asup:smf_name>aggregate</asup:smf_name>
	<asup:ui_name>Aggregate Name</asup:ui_name>
	<asup:type>aggr_name</asup:type>
	<asup:qualification>create</asup:qualification>
	<asup:remap>hash</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>state</asup:tag>
	<asup:smf_name>state</asup:smf_name>
	<asup:ui_name>Volume State</asup:ui_name>
	<asup:type>volState_enum</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>type</asup:tag>
	<asup:smf_name>type</asup:smf_name>
	<asup:ui_name>Volume Type</asup:ui_name>
	<asup:type>ui_voltype</asup:type>
	<asup:qualification>create</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>style</asup:tag>
	<asup:smf_name>volume-style</asup:smf_name>
	<asup:ui_name>Volume Style</asup:ui_name>
	<asup:type>volStyle</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>styleEx</asup:tag>
	<asup:smf_name>volume-style-extended</asup:smf_name>
	<asup:ui_name>Extended Volume Style</asup:ui_name>
	<asup:type>volume_type</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>policy</asup:tag>
	<asup:smf_name>policy</asup:smf_name>
	<asup:ui_name>Export Policy</asup:ui_name>
	<asup:type>text</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>hash</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>usr</asup:tag>
	<asup:smf_name>user</asup:smf_name>
	<asup:ui_name>User ID</asup:ui_name>
	<asup:type>userid</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>hash</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>grp</asup:tag>
	<asup:smf_name>group</asup:smf_name>
	<asup:ui_name>Group ID</asup:ui_name>
	<asup:type>groupid</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>hash</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>security_style</asup:tag>
	<asup:smf_name>security-style</asup:smf_name>
	<asup:ui_name>Security Style</asup:ui_name>
	<asup:type>security_style_enum</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>unix_perm</asup:tag>
	<asup:smf_name>unix-permissions</asup:smf_name>
	<asup:ui_name>UNIX Permissions</asup:ui_name>
	<asup:type>unix_perm</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>j_path</asup:tag>
	<asup:smf_name>junction-path</asup:smf_name>
	<asup:ui_name>Junction Path</asup:ui_name>
	<asup:type>junction_path</asup:type>
	<asup:qualification>create</asup:qualification>
	<asup:remap>hash</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>j_path_src</asup:tag>
	<asup:smf_name>junction-path-source</asup:smf_name>
	<asup:ui_name>Junction Path Source</asup:ui_name>
	<asup:type>juncpath_src_enum</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>hash</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>j_actv</asup:tag>
	<asup:smf_name>junction-active</asup:smf_name>
	<asup:ui_name>Junction Active</asup:ui_name>
	<asup:type>boolean</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>parent</asup:tag>
	<asup:smf_name>junction-parent</asup:smf_name>
	<asup:ui_name>Junction Parent Volume</asup:ui_name>
	<asup:type>volume_name</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>hash</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>vsroot</asup:tag>
	<asup:smf_name>vsroot</asup:smf_name>
	<asup:ui_name>Vserver Root Volume</asup:ui_name>
	<asup:type>boolean</asup:type>
	<asup:qualification>create</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>comment</asup:tag>
	<asup:smf_name>comment</asup:smf_name>
	<asup:ui_name>Comment</asup:ui_name>
	<asup:type>text</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>hash</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>size</asup:tag>
	<asup:smf_name>size</asup:smf_name>
	<asup:ui_name>Volume Size</asup:ui_name>
	<asup:type>size</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>avail</asup:tag>
	<asup:smf_name>available</asup:smf_name>
	<asup:ui_name>Available Size</asup:ui_name>
	<asup:type>size</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>total</asup:tag>
	<asup:smf_name>total</asup:smf_name>
	<asup:ui_name>Total User-Visible Size</asup:ui_name>
	<asup:type>size</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>used</asup:tag>
	<asup:smf_name>used</asup:smf_name>
	<asup:ui_name>Used Size</asup:ui_name>
	<asup:type>size</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>pcnt_used</asup:tag>
	<asup:smf_name>percent-used</asup:smf_name>
	<asup:ui_name>Used Percentage</asup:ui_name>
	<asup:type>percent</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>exp_avail_size</asup:tag>
	<asup:smf_name>expected-available</asup:smf_name>
	<asup:ui_name>Expected Available Size</asup:ui_name>
	<asup:type>size</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>over_provisioned_size</asup:tag>
	<asup:smf_name>over-provisioned</asup:smf_name>
	<asup:ui_name>Over Provisioned Size</asup:ui_name>
	<asup:type>size</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>snap_rsrv_avail_size</asup:tag>
	<asup:smf_name>snapshot-reserve-available</asup:smf_name>
	<asup:ui_name>Available Snapshot Reserve Size</asup:ui_name>
	<asup:type>size</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>nearly_full_threshold</asup:tag>
	<asup:smf_name>space-nearly-full-threshold-percent</asup:smf_name>
	<asup:ui_name>Volume Nearly Full Threshold Percent</asup:ui_name>
	<asup:type>percent</asup:type>
	<asup:qualification>modify</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>full_threshold</asup:tag>
	<asup:smf_name>space-full-threshold-percent</asup:smf_name>
	<asup:ui_name>Volume Full Threshold Percent</asup:ui_name>
	<asup:type>percent</asup:type>
	<asup:qualification>modify</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>autosz</asup:tag>
	<asup:smf_name>autosize</asup:smf_name>
	<asup:ui_name>Autosize Enabled</asup:ui_name>
	<asup:type>boolean</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>max_autosz</asup:tag>
	<asup:smf_name>max-autosize</asup:smf_name>
	<asup:ui_name>Maximum Autosize</asup:ui_name>
	<asup:type>size</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>min_autosz</asup:tag>
	<asup:smf_name>min-autosize</asup:smf_name>
	<asup:ui_name>Minimum Autosize</asup:ui_name>
	<asup:type>size</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>autosz_grow_thresh_pcnt</asup:tag>
	<asup:smf_name>autosize-grow-threshold-percent</asup:smf_name>
	<asup:ui_name>Autosize Grow Threshold Percentage</asup:ui_name>
	<asup:type>percent</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>autosz_shrink_thresh_pcnt</asup:tag>
	<asup:smf_name>autosize-shrink-threshold-percent</asup:smf_name>
	<asup:ui_name>Autosize Shrink Threshold Percentage</asup:ui_name>
	<asup:type>percent</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>autosz_mode</asup:tag>
	<asup:smf_name>autosize-mode</asup:smf_name>
	<asup:ui_name>Autosize Mode</asup:ui_name>
	<asup:type>autosize_mode_enum</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>files</asup:tag>
	<asup:smf_name>files</asup:smf_name>
	<asup:ui_name>Total Files (for user-visible data)</asup:ui_name>
	<asup:type>unsigned64</asup:type>
	<asup:qualification>modify</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>files_used</asup:tag>
	<asup:smf_name>files-used</asup:smf_name>
	<asup:ui_name>Files Used (for user-visible data)</asup:ui_name>
	<asup:type>unsigned64_chartable</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>inofile_version</asup:tag>
	<asup:smf_name>inofile-version</asup:smf_name>
	<asup:ui_name>Inofile Version</asup:ui_name>
	<asup:type>unsigned</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>maxdir_size</asup:tag>
	<asup:smf_name>maxdir-size</asup:smf_name>
	<asup:ui_name>Maximum Directory Size</asup:ui_name>
	<asup:type>size</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>space_guarantee</asup:tag>
	<asup:smf_name>space-guarantee</asup:smf_name>
	<asup:ui_name>Space Guarantee Style</asup:ui_name>
	<asup:type>space_guarantee_enum</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>is_space_guarantee_en</asup:tag>
	<asup:smf_name>space-guarantee-enabled</asup:smf_name>
	<asup:ui_name>Space Guarantee in Effect</asup:ui_name>
	<asup:type>boolean</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>min_rdahead</asup:tag>
	<asup:smf_name>min-readahead</asup:smf_name>
	<asup:ui_name>Minimum Read Ahead</asup:ui_name>
	<asup:type>boolean</asup:type>
	<asup:qualification>modify</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>atime_update</asup:tag>
	<asup:smf_name>atime-update</asup:smf_name>
	<asup:ui_name>Access Time Update Enabled</asup:ui_name>
	<asup:type>boolean</asup:type>
	<asup:qualification>modify</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>snapdir_access</asup:tag>
	<asup:smf_name>snapdir-access</asup:smf_name>
	<asup:ui_name>Snapshot Directory Access Enabled</asup:ui_name>
	<asup:type>boolean</asup:type>
	<asup:qualification>modify</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>pcnt_snap_space</asup:tag>
	<asup:smf_name>percent-snapshot-space</asup:smf_name>
	<asup:ui_name>Space Reserved for Snapshot Copies</asup:ui_name>
	<asup:type>percent</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>snap_policy</asup:tag>
	<asup:smf_name>snapshot-policy</asup:smf_name>
	<asup:ui_name>Snapshot Policy</asup:ui_name>
	<asup:type>snapshot_policy</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>hash</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>c_time</asup:tag>
	<asup:smf_name>create-time</asup:smf_name>
	<asup:ui_name>Creation Time</asup:ui_name>
	<asup:type>Date</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>lang</asup:tag>
	<asup:smf_name>language</asup:smf_name>
	<asup:ui_name>Language</asup:ui_name>
	<asup:type>language_code</asup:type>
	<asup:qualification>create</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>oem_char_set</asup:tag>
	<asup:smf_name>oem-character-set</asup:smf_name>
	<asup:ui_name>OEM Character Set</asup:ui_name>
	<asup:type>text</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>nfs_char_set</asup:tag>
	<asup:smf_name>nfs-character-set</asup:smf_name>
	<asup:ui_name>NFS Character Set</asup:ui_name>
	<asup:type>text</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>max_write_alloc_blks</asup:tag>
	<asup:smf_name>max-write-alloc-blocks</asup:smf_name>
	<asup:ui_name>Maximum Write Allocation Blocks</asup:ui_name>
	<asup:type>unsigned</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>name_ordinal</asup:tag>
	<asup:smf_name>name-ordinal</asup:smf_name>
	<asup:ui_name>Name Ordinal</asup:ui_name>
	<asup:type>text</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>is_clust_vol</asup:tag>
	<asup:smf_name>is-cluster-volume</asup:smf_name>
	<asup:ui_name>Is Cluster-Mode Volume</asup:ui_name>
	<asup:type>boolean</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>used_snap_rsrv_pcnt</asup:tag>
	<asup:smf_name>snapshot-space-used</asup:smf_name>
	<asup:ui_name>Snapshot Reserve Used</asup:ui_name>
	<asup:type>percent_no_limit</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>clone_vol</asup:tag>
	<asup:smf_name>clone-volume</asup:smf_name>
	<asup:ui_name>Clone Volume</asup:ui_name>
	<asup:type>boolean</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>anti_virus_on_access_policy</asup:tag>
	<asup:smf_name>antivirus-on-access-policy</asup:smf_name>
	<asup:ui_name>Antivirus On-Access Policy</asup:ui_name>
	<asup:type>antivirus_policy</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>vol_uuid</asup:tag>
	<asup:smf_name>uuid</asup:smf_name>
	<asup:ui_name>UUID of the Volume</asup:ui_name>
	<asup:type>Uuid</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>load_share_src</asup:tag>
	<asup:smf_name>load-sharing-source</asup:smf_name>
	<asup:ui_name>Load Sharing Source Volume</asup:ui_name>
	<asup:type>volume_name</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>hash</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>move_target</asup:tag>
	<asup:smf_name>move-target</asup:smf_name>
	<asup:ui_name>Move Target Volume</asup:ui_name>
	<asup:type>boolean</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>fs_inconsistency</asup:tag>
	<asup:smf_name>is-inconsistent</asup:smf_name>
	<asup:ui_name>Inconsistency in the File System</asup:ui_name>
	<asup:type>boolean</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>is_rdonly</asup:tag>
	<asup:smf_name>is-readonly</asup:smf_name>
	<asup:ui_name>Is Read-Only Volume</asup:ui_name>
	<asup:type>boolean</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>i_uuid</asup:tag>
	<asup:smf_name>instance-uuid</asup:smf_name>
	<asup:ui_name>Instance UUID of the Volume</asup:ui_name>
	<asup:type>Uuid</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>p_uuid</asup:tag>
	<asup:smf_name>provenance-uuid</asup:smf_name>
	<asup:ui_name>Provenance UUID of the Volume</asup:ui_name>
	<asup:type>Uuid</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>nvfail_option</asup:tag>
	<asup:smf_name>nvfail</asup:smf_name>
	<asup:ui_name>NVFAIL Option</asup:ui_name>
	<asup:type>OnOff</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>in_nvfailed_state</asup:tag>
	<asup:smf_name>in-nvfailed-state</asup:smf_name>
	<asup:ui_name>Volume&apos;s NVFAIL State</asup:ui_name>
	<asup:type>boolean</asup:type>
	<asup:qualification>modify</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>dr_force_nvfail_option</asup:tag>
	<asup:smf_name>dr-force-nvfail</asup:smf_name>
	<asup:ui_name>Force NVFAIL on MetroCluster Switchover</asup:ui_name>
	<asup:type>OnOff</asup:type>
	<asup:qualification>modify</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>blk_type</asup:tag>
	<asup:smf_name>block-type</asup:smf_name>
	<asup:ui_name>Block Type</asup:ui_name>
	<asup:type>blockType</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>hya_eligibility</asup:tag>
	<asup:smf_name>hybrid-cache-eligibility</asup:smf_name>
	<asup:ui_name>Flash Pool Caching Eligibility</asup:ui_name>
	<asup:type>volHyaEligibility_enum</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>hya_wc_ineligibility_reason</asup:tag>
	<asup:smf_name>hybrid-cache-write-caching-ineligibility-reason</asup:smf_name>
	<asup:ui_name>Flash Pool Write Caching Ineligibility Reason</asup:ui_name>
	<asup:type>text</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>caching_policy</asup:tag>
	<asup:smf_name>caching-policy</asup:smf_name>
	<asup:ui_name>Caching Policy Name</asup:ui_name>
	<asup:type>text</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>cache_retention_priority</asup:tag>
	<asup:smf_name>cache-retention-priority</asup:smf_name>
	<asup:ui_name>Cache Retention Priority</asup:ui_name>
	<asup:type>cacheRetPri_enum</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>autobalance_aggr_enabled</asup:tag>
	<asup:smf_name>is-autobalance-eligible</asup:smf_name>
	<asup:ui_name>Is Eligible for Auto Balance Aggregate</asup:ui_name>
	<asup:type>boolean</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>role</asup:tag>
	<asup:smf_name>constituent-role</asup:smf_name>
	<asup:ui_name>Constituent Volume Role</asup:ui_name>
	<asup:type>repos_constituent_role</asup:type>
	<asup:qualification>create</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>fgMsid</asup:tag>
	<asup:smf_name>flexgroup-msid</asup:smf_name>
	<asup:ui_name>FlexGroup Master Data Set ID</asup:ui_name>
	<asup:type>unsigned64</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>fgIndex</asup:tag>
	<asup:smf_name>flexgroup-index</asup:smf_name>
	<asup:ui_name>FlexGroup Index</asup:ui_name>
	<asup:type>unsigned</asup:type>
	<asup:qualification>modify</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>fgUuid</asup:tag>
	<asup:smf_name>flexgroup-uuid</asup:smf_name>
	<asup:ui_name>UUID of the FlexGroup</asup:ui_name>
	<asup:type>Uuid</asup:type>
	<asup:qualification>read</asup:qualification>
	<asup:remap>noop</asup:remap>
</asup:field>
<asup:field>
	<asup:tag>maxConstSize</asup:tag>
	<asup:smf_name>max-constituent-size</asup:smf_name>
	<asup:ui_name>Maximum size of a FlexGroup Constituent</asup:ui_name>
	<asup:type>size</asup:type>
	<asup:qualification>write</asup:qualification>
	<asup:remap>noop</asup:remap>